const view=document.getElementById("view"),title=document.getElementById("pageTitle"),navs=[...document.querySelectorAll(".nav")];
const pages={dashboard:["Overview","Network-wide status at a glance"],node:["My Node","Your identity, runtime and listening endpoint"],network:["Peers & Connections","Discover and connect to AWEp2P nodes"],federation:["AWENET","Build Nodes, Data Centres and Data Groups"],storage:["Storage","Local and distributed data plane"],messenger:["Messenger","Peer-to-peer messaging"],store:["AWEStore","AWE modules and services"],security:["Security","Identity, transport and trust"],diagnostics:["Diagnostics","Health checks and runtime inspection"],settings:["Settings","Application configuration"]};
let live={status:"starting",node_id:"loading",node_address:"loading",transport:"loading",ui:"connecting",peers:[],node:{},storage:{},security:{},federation:{}};

function apiBase(){return localStorage.getItem("aweApiBase")||""}
async function api(path,options={}){const r=await fetch(apiBase()+path,options);if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadMessenger(){try{const d=await api("/api/messenger");const box=document.getElementById("messageList");if(box)box.innerHTML=d.messages.length?d.messages.map(m=>'<div class="list-row"><span>'+esc(m.recipient)+'</span><b>'+esc(m.state)+'</b><span>'+esc(m.text)+'</span></div>').join(""):'<div class="empty">No queued messages.</div>'}catch(e){}}\nasync function refresh(){
 try{const [status,node,storage,security,federation]=await Promise.all([api("/api/status"),api("/api/node"),api("/api/storage"),api("/api/security"),api("/api/federation")]);live={...status,node,storage,security,federation};setConnection(true)}
 catch(e){live={...live,status:"offline",ui:"disconnected",peers:[]};setConnection(false)}
}
function setConnection(on){document.getElementById("sideDot").classList.toggle("online",on);document.getElementById("sideState").textContent=on?"Node online":"Disconnected";document.getElementById("sideTransport").textContent=on?live.transport:"API unavailable";document.getElementById("apiBadge").textContent="API · "+(on?live.ui:"offline")}
function esc(x){return String(x??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function card(a,b,c="Live runtime"){return '<div class="card"><div class="metric-label">'+a+'</div><div class="metric">'+esc(b)+'</div><div class="muted">'+c+'</div></div>'}
function panel(h,body,extra=""){return '<div class="section panel"><div class="section-head"><h2>'+h+'</h2>'+extra+'</div>'+body+'</div>'}
function peerRows(){return live.peers.length?live.peers.map(p=>'<tr><td><div class="peer"><i class="peer-dot"></i><b>'+esc(p.id)+'</b></div></td><td>'+esc(p.address)+'</td><td>'+esc(p.last_seen)+'</td><td><span class="status"><i></i>Discovered</span></td></tr>').join(""):'<tr><td colspan="4" class="empty">No peers are currently known to this node.</td></tr>'}
function render(k){
 const p=pages[k]||pages.dashboard;navs.forEach(n=>n.classList.toggle("active",n.dataset.view===k));title.textContent=p[0];
 let body="";
 if(k==="dashboard"){
  body='<div class="grid">'+card("Node status",live.status.toUpperCase())+card("Data centre",live.node?.descriptor?"Node registered":"Local node","Live node descriptor")+card("Node ID",live.node_id,"AWE identity")+card("Connected peers",live.status?.active_connections||0,"Authenticated live connections")+card("Transport",live.transport,"Node transport")+'</div>'+
  '<div class="section two">'+panel("Network topology",'<div class="network-map"><div class="node-point main" style="left:49%;top:47%"></div>'+live.peers.slice(0,8).map((_,i)=>{const a=i*45;return '<div class="line" style="left:51%;top:51%;width:105px;transform:rotate('+a+'deg)"></div><div class="node-point" style="left:'+(50+34*Math.cos(a*Math.PI/180))+'%;top:'+(50+34*Math.sin(a*Math.PI/180))+'%"></div>'}).join("")+'</div>'),panel("Runtime health",'<div class="big-status"><div class="big-orb">'+(live.status==="online"?"✓":"!")+'</div><div><b>'+esc(live.status==="online"?"Node operational":"Node unavailable")+'</b><div class="detail">'+esc(live.node_address)+'</div></div></div><div class="list section"><div class="list-row"><span>Core API</span><span class="status"><i></i>'+esc(live.ui)+'</span></div><div class="list-row"><span>Known peers</span><b>'+live.peers.length+'</b></div></div>'))+
  panel("Known peers",'<table class="table"><thead><tr><th>Peer</th><th>Address</th><th>Last seen</th><th>State</th></tr></thead><tbody>'+peerRows()+'</tbody></table>','<button class="secondary" id="goNetwork">Manage</button>');
 } else if(k==="node"){
  body='<div class="grid">'+card("Status",live.status.toUpperCase())+card("Identity",live.node_id,"Public AWE identity")+card("Listen",live.node_address,"Local node endpoint")+card("Transport",live.transport,"Active protocol")+'</div>'+
  panel("Identity",'<div class="list"><div class="list-row"><span>AWE Node ID</span><b>'+esc(live.node_id)+'</b></div><div class="list-row"><span>Listen address</span><b>'+esc(live.node_address)+'</b></div><div class="list-row"><span>Transport</span><b>'+esc(live.transport)+'</b></div><div class="list-row"><span>Known peers</span><b>'+live.peers.length+'</b></div></div>')+
  panel("Runtime",'<div class="notice">This screen represents the actual local Rust node. Identity and endpoint values come from the running node API.</div>');
 } else if(k==="network"){
  body=panel("Connect to node",'<div class="peer-form"><input id="peerAddress" placeholder="127.0.0.1:41000"><button class="primary" id="connectBtn">Connect</button></div><div class="muted" style="margin-top:8px">Enter a reachable AWEp2P node address. The Rust node performs bootstrap/discovery.</div>')+
  panel("Known peers",'<table class="table"><thead><tr><th>Peer</th><th>Address</th><th>Last seen</th><th>State</th></tr></thead><tbody>'+peerRows()+'</tbody></table>','<button class="secondary" id="peerRefresh">Refresh</button>')+
  panel("Topology",'<div class="network-map"><div class="node-point main" style="left:49%;top:47%"></div>'+live.peers.map((_,i)=>{const a=i*(360/Math.max(live.peers.length,1));return '<div class="line" style="left:51%;top:51%;width:100px;transform:rotate('+a+'deg)"></div><div class="node-point" style="left:'+(50+35*Math.cos(a*Math.PI/180))+'%;top:'+(50+35*Math.sin(a*Math.PI/180))+'%"></div>'}).join("")+'</div>');
 else if(k==="federation"){
  body=panel("AWENET identity",'<div class="grid">'+card("Node",live.node_id,"Current local identity")+card("Data centre",live.federation?.data_centre_id||"Not joined","Current membership")+card("Data group",live.federation?.data_group_id||"Not joined","Current membership")+card("Centres",live.federation?.joined_data_centres?.length||0,"Imported .awenode/.awedc memberships")+card("Live links",live.status?.active_connections||0,"Authenticated transport connections")+card("Groups",live.federation?.joined_data_groups?.length||0,"Imported .dgc memberships")+'</div>')+
  panel("1 · Create .awenode",'<div class="peer-form"><input id="fedNodeName" placeholder="Data centre name"><input id="fedNodeDcId" placeholder="Existing Data centre ID (optional)"><input id="fedEndpoint" placeholder="'+esc(live.node_address)+'"><input id="fedBootstrap" placeholder="Owner endpoints: host:41000,host2:41000"><button class="primary" id="genNode">Generate</button></div><div class="muted" style="margin-top:8px">Install this configuration on another AWEp2P node and import it from this screen to join the same data centre.</div>')+
  panel("2 · Create .awedc",'<div class="peer-form"><input id="fedDcId" placeholder="Data centre ID"><input id="fedDcName" placeholder="Data centre name"><input id="fedEndpoints" placeholder="host:41000,host2:41000"><button class="primary" id="genDc">Generate</button></div><div class="muted" style="margin-top:8px">The data-centre package describes the owner, member nodes and reachable transport endpoints.</div>')+
  panel("3 · Create .dgc",'<div class="peer-form"><input id="fedOwnerDc" placeholder="Owner data centre ID"><input id="fedGroupName" placeholder="Data group name"><input id="fedCentres" placeholder="dc-1,dc-2,dc-3"><button class="primary" id="genDgc">Generate</button></div><div class="muted" style="margin-top:8px">A data group joins data centres into a higher-level AWENET group.</div>')+
  panel("Import configuration",'<div class="peer-form"><select id="fedKind"><option value="awenode">.awenode — Node → Data Centre</option><option value="awedc">.awedc — Data Centre → Data Centre</option><option value="dgc">.dgc — Data Group → Data Group</option></select><input type="file" id="fedFile" accept=".awenode,.awedc,.dgc,application/json"><button class="primary" id="importFed">Import & Join</button></div><div id="fedResult" class="notice" style="margin-top:10px">Choose a configuration file. The Rust core validates its format before accepting it.</div>');
 } else if(k==="storage"){
  const used=localStorage.getItem("aweStoragePath")||"Node-managed storage";
  const free=live.storage.free_bytes||0;
  const usedBytes=live.storage.used_bytes||0;
  const fmt=n=>{n=Number(n)||0;if(n<1024)return n+" B";if(n<1048576)return (n/1024).toFixed(1)+" KB";if(n<1073741824)return (n/1048576).toFixed(1)+" MB";return (n/1073741824).toFixed(2)+" GB"};
  body='<div class="grid">'+card("Data plane","Active","Storage subsystem")+card("Used",fmt(usedBytes),"Local content-addressed objects")+card("Free",fmt(free),"Available disk space")+card("Policy","1000 × 3","Shards × replicas")+'</div>'+
  panel("Upload file",'<div class="peer-form"><input type="file" id="storageFile"><button class="primary" id="uploadStorage">Upload & Replicate</button></div><div id="storageUploadResult" class="notice" style="margin-top:10px">The Rust node encodes, stores and replicates the file. The UI only sends the selected bytes.</div>')+
  panel("Download / reconstruct",'<div class="peer-form"><input id="downloadFileId" placeholder="File ID (64 hex characters)"><button class="primary" id="downloadStorage">Reconstruct & Download</button></div><div id="storageDownloadResult" class="notice" style="margin-top:10px">AWEp2P will retrieve missing remote shards when needed and reconstruct the original file.</div>')+
  panel("Storage details",'<div class="list"><div class="list-row"><span>Storage root</span><b>'+esc(live.storage.root||used)+'</b></div><div class="list-row"><span>Objects</span><b>'+esc(live.storage.objects||0)+'</b></div><div class="list-row"><span>Healthy replicas</span><b>'+esc(live.storage.healthy_replicas||0)+'</b></div><div class="list-row"><span>Repaired chunks</span><b>'+esc(live.storage.repaired_chunks||0)+'</b></div></div>');
 } else if(k==="messenger"){
  body=panel("Messenger",'<div class="peer-form"><input id="msgRecipient" placeholder="Recipient AWE ID"><input id="msgText" placeholder="Message"><button class="primary" id="sendMsg">Send</button></div><div id="msgState" class="muted" style="margin-top:8px">Messages are queued locally until transport delivery is available.</div>')+
  panel("Local message queue",'<div id="messageList" class="list"><div class="empty">Loading…</div></div>');
 } else if(k==="store"){
  body='<div class="store-grid"><div class="card store-card"><div class="store-icon">◈</div><b>AWE Core</b><p>Core networking, identity, routing and node services.</p><span class="status"><i></i>Installed</span></div><div class="card store-card"><div class="store-icon">◎</div><b>Node Dashboard</b><p>Local management interface for your AWEp2P node.</p><span class="status"><i></i>Installed</span></div><div class="card store-card"><div class="store-icon">+</div><b>Modules</b><p>Future AWEStore packages will be managed here.</p><span class="pill">Catalog API needed</span></div></div>';
 } else if(k==="security"){
  body='<div class="grid">'+card("Identity",live.node_id,"Public node identity")+card("Transport",live.transport,"Network layer")+card("Peer count",live.peers.length,"Known peers")+card("Trust","Core-managed","No UI-only security state")+'</div>'+
  panel("Security model",'<div class="list"><div class="list-row"><span>Node identity</span><b>Rust core</b></div><div class="list-row"><span>Authentication</span><b>Core protocol</b></div><div class="list-row"><span>Transport</span><b>'+esc(live.transport)+'</b></div><div class="list-row"><span>Secrets</span><b>Local identity vault</b></div></div>');
 } else if(k==="diagnostics"){
  body='<div class="grid">'+card("Node",live.status.toUpperCase(),"Live API status")+card("API",live.ui,"Dashboard connection")+card("Peers",live.peers.length,"Known peers")+card("Endpoint",live.node_address,"Listen endpoint")+'</div>'+
  panel("Runtime diagnostics",'<div class="terminal"><div>$ GET /api/status</div><div class="green">200 · '+esc(live.status)+'</div><div>$ node</div><div class="green">'+esc(live.node_id)+'</div><div>$ peers</div><div class="green">'+live.peers.length+' known peer(s)</div></div>','<button class="primary" id="healthBtn">Run health check</button>')+
  panel("Result",'<div id="healthResult" class="notice">Press “Run health check” to query the live node health endpoint.</div>');
 } else if(k==="settings"){
  body=panel("Node API",'<div class="peer-form"><input id="apiBase" placeholder="http://192.168.1.10:41800" value="'+esc(apiBase())+'"><button class="primary" id="saveApi">Save & Test</button></div><div class="muted" style="margin-top:8px">Leave empty for the bundled local desktop node. Android can point to a reachable node API.</div>')+
  panel("Interface",'<div class="list"><div class="list-row"><span>Theme</span><b>System UI</b></div><div class="list-row"><span>Auto refresh</span><b>5 seconds</b></div><div class="list-row"><span>API mode</span><b>'+esc(apiBase()||"Local")+'</b></div></div>');
 }
 view.innerHTML='<div class="content"><div class="hero"><div><h1>'+p[0]+'</h1><p>'+p[1]+'</p></div><div class="actions"><button class="secondary" id="refreshBtn">Refresh</button></div></div>'+body+'</div>';
 bind(k);
}
function bind(k){
 const r=document.getElementById("refreshBtn");if(r)r.onclick=async()=>{await refresh();render(k)};
 const g=document.getElementById("goNetwork");if(g)g.onclick=()=>render("network");
 const pr=document.getElementById("peerRefresh");if(pr)pr.onclick=async()=>{await refresh();render("network")};
 const cb=document.getElementById("connectBtn");if(cb)cb.onclick=async()=>{const a=document.getElementById("peerAddress").value.trim();if(!a)return toast("Enter a node address");cb.disabled=true;try{const x=await api("/api/connect?address="+encodeURIComponent(a),{method:"POST"});toast("Bootstrap complete");await refresh();render("network")}catch(e){toast("Connection failed: "+e.message)}finally{cb.disabled=false}};
 const sa=document.getElementById("saveApi");if(sa)sa.onclick=async()=>{localStorage.setItem("aweApiBase",document.getElementById("apiBase").value.trim().replace(/\/$/,""));await refresh();render("settings");toast("API endpoint saved")};
 const ss=document.getElementById("saveStorage");if(ss)ss.onclick=()=>{localStorage.setItem("aweStoragePath",document.getElementById("storagePath").value.trim());toast("Storage preference saved")};
 const up=document.getElementById("uploadStorage");if(up)up.onclick=async()=>{const file=document.getElementById("storageFile").files[0],box=document.getElementById("storageUploadResult");if(!file)return toast("Choose a file first");if(file.size>64*1024*1024)return toast("Maximum upload size is 64 MB");up.disabled=true;try{const buf=await file.arrayBuffer(),bytes=new Uint8Array(buf);let hex="";for(const b of bytes)hex+=b.toString(16).padStart(2,"0");const r=await api("/api/storage/put",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({filename:file.name,data_hex:hex})});box.textContent="Stored: "+r.file_id+" · "+r.status+" · "+(r.sent_remote||0)+" remote replica transfers";document.getElementById("downloadFileId").value=r.file_id;await refresh();render("storage")}catch(e){box.textContent="Upload failed: "+e.message}finally{up.disabled=false}};
 const dl=document.getElementById("downloadStorage");if(dl)dl.onclick=async()=>{const id=document.getElementById("downloadFileId").value.trim(),box=document.getElementById("storageDownloadResult");if(!/^[0-9a-fA-F]{64}$/.test(id))return toast("Enter a valid 64-hex file ID");dl.disabled=true;try{const r=await api("/api/storage/get?file_id="+encodeURIComponent(id));const raw=r.data_hex||"";const bytes=new Uint8Array(raw.length/2);for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(raw.slice(i*2,i*2+2),16);const blob=new Blob([bytes],{type:"application/octet-stream"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=r.filename||"awep2p-file";a.click();URL.revokeObjectURL(a.href);box.textContent="Reconstructed and downloaded: "+r.filename+" · "+r.size+" bytes"}catch(e){box.textContent="Download failed: "+e.message}finally{dl.disabled=false}};
 const hb=document.getElementById("healthBtn");if(hb)hb.onclick=async()=>{const box=document.getElementById("healthResult");try{const x=await api("/api/health");box.innerHTML='<span class="status"><i></i>Health check passed</span><div class="detail" style="margin-top:8px">'+esc(JSON.stringify(x))+'</div>'}catch(e){box.textContent="Health check failed: "+e.message}};
  const gen=async(kind,payload)=>{try{const r=await api("/api/federation/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,...payload})});if(r.status!=="generated")throw new Error(r.error||"generation failed");const blob=new Blob([r.content],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=r.filename;a.click();URL.revokeObjectURL(a.href);toast("Generated "+r.filename)}catch(e){toast("Generation failed: "+e.message)}};
  const gn=document.getElementById("genNode");if(gn)gn.onclick=()=>gen("awenode",{name:document.getElementById("fedNodeName").value.trim()||"AWE Data Centre",endpoint:document.getElementById("fedEndpoint").value.trim()||live.node_address,bootstrap:document.getElementById("fedBootstrap").value.split(",").map(x=>x.trim()).filter(Boolean),data_centre_id:document.getElementById("fedNodeDcId")?.value.trim()||live.federation?.data_centre_id||""});
  const gd=document.getElementById("genDc");if(gd)gd.onclick=()=>gen("awedc",{data_centre_id:document.getElementById("fedDcId").value.trim(),name:document.getElementById("fedDcName").value.trim()||"AWE Data Centre",endpoints:document.getElementById("fedEndpoints").value.split(",").map(x=>x.trim()).filter(Boolean)});
  const gg=document.getElementById("genDgc");if(gg)gg.onclick=()=>gen("dgc",{owner_data_centre_id:document.getElementById("fedOwnerDc").value.trim(),name:document.getElementById("fedGroupName").value.trim()||"AWE Data Group",data_centre_ids:document.getElementById("fedCentres").value.split(",").map(x=>x.trim()).filter(Boolean)});
  const imp=document.getElementById("importFed");if(imp)imp.onclick=async()=>{const file=document.getElementById("fedFile").files[0],box=document.getElementById("fedResult");if(!file)return toast("Choose a configuration file");imp.disabled=true;try{const content=await file.text(),kind=document.getElementById("fedKind").value,r=await api("/api/federation/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,content})});if(r.status!=="imported")throw new Error(r.error||"import failed");box.textContent="Imported successfully. AWENET membership is now stored in this running node.";await refresh();render("federation");toast("AWENET configuration imported")}catch(e){box.textContent="Import failed: "+e.message}finally{imp.disabled=false}};
 const sm=document.getElementById("sendMsg");if(sm)sm.onclick=async()=>{const recipient=document.getElementById("msgRecipient").value.trim(),message=document.getElementById("msgText").value.trim(),state=document.getElementById("msgState");if(!recipient||!message)return toast("Recipient and message are required");sm.disabled=true;try{const r=await api("/api/messenger/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipient,text:message})});state.textContent="Queued: "+r.message.id;document.getElementById("msgText").value="";await loadMessenger()}catch(e){state.textContent="Send failed: "+e.message}finally{sm.disabled=false}};
}
function toast(t){const e=document.createElement("div");e.textContent=t;e.style="position:fixed;right:22px;bottom:22px;background:#111829;color:#fff;padding:11px 15px;border-radius:9px;font-size:11px;z-index:10";document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
navs.forEach(n=>n.addEventListener("click",()=>render(n.dataset.view)));
(async()=>{await refresh();render("dashboard");setInterval(async()=>{await refresh();if(title.textContent===pages.dashboard[0])render("dashboard")},5000)})();