const view=document.getElementById("view"),title=document.getElementById("pageTitle"),navs=[...document.querySelectorAll(".nav")];
const pages={dashboard:["Overview","Your AWE network at a glance"],node:["My Node","Manage the local node and its storage"],profile:["My Profile","Private local profile settings"],sites:["My Sites","Create, edit, open and remove your sites"],saved:["Saved","Your saved sites and resources"],network:["Connections","Connect to devices without exposing user profile data"],federation:["AWENET","Manage Node, Data Centre and Data Group membership"],storage:["Node Storage","Choose local data and serve it through your node"],messenger:["Messenger","Peer-to-peer messaging"],store:["AWEStore","Installed and available AWE modules"],security:["Security","Identity, transport and trust"],diagnostics:["Diagnostics","Live node health and diagnostics"],settings:["Settings","Application configuration"]};
let live={status:"starting",node_id:"loading",node_address:"loading",transport:"loading",ui:"connecting",peers:[],node:{},storage:{},security:{},federation:{}};

function apiBase(){return localStorage.getItem("aweApiBase")||""}
async function api(path,options={}){const r=await fetch(apiBase()+path,options);if(!r.ok)throw new Error(await r.text());return r.json()}
function esc(x){return String(x??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function jsonStore(k,fallback=[]){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(fallback))}catch{return fallback}}
function saveStore(k,v){localStorage.setItem(k,JSON.stringify(v))}
function toast(t){const e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2400)}
function card(a,b,c="Live runtime"){return '<div class="card"><div class="metric-label">'+a+'</div><div class="metric">'+esc(b)+'</div><div class="muted">'+c+'</div></div>'}
function panel(h,body,extra=""){return '<div class="section panel"><div class="section-head"><h2>'+h+'</h2>'+extra+'</div>'+body+'</div>'}
function setConnection(on){document.getElementById("sideDot").classList.toggle("online",on);document.getElementById("sideState").textContent=on?"Node online":"Disconnected";document.getElementById("sideTransport").textContent=on?live.transport:"API unavailable";document.getElementById("apiBadge").textContent="API · "+(on?live.ui:"offline")}
async function refresh(){try{const [status,node,storage,security,federation]=await Promise.all([api("/api/status"),api("/api/node"),api("/api/storage"),api("/api/security"),api("/api/federation")]);live={...status,node,storage,security,federation};setConnection(true)}catch(e){live={...live,status:"offline",ui:"disconnected",peers:[]};setConnection(false)}}
function peerRows(){return live.peers.length?live.peers.map(p=>'<tr><td><div class="peer"><i class="peer-dot"></i><b>'+esc(p.device_id||p.id)+'</b></div></td><td>'+esc(p.address||"—")+'</td><td>'+esc(p.last_seen||"—")+'</td><td><span class="status"><i></i>Connected</span></td></tr>').join(""):'<tr><td colspan="4" class="empty">No connected devices.</td></tr>'}
function fmt(n){n=Number(n)||0;if(n<1024)return n+" B";if(n<1048576)return(n/1024).toFixed(1)+" KB";if(n<1073741824)return(n/1048576).toFixed(1)+" MB";return(n/1073741824).toFixed(2)+" GB"}

function render(k){const p=pages[k]||pages.dashboard;navs.forEach(n=>n.classList.toggle("active",n.dataset.view===k));title.textContent=p[0];let body="";
if(k==="dashboard"){body='<div class="grid">'+card("Node",live.status.toUpperCase())+card("Device ID",live.device_id||"—","Private connection identifier")+card("Connected devices",live.status?.active_connections||0,"Authenticated device links")+card("Storage",fmt(live.storage.used_bytes),"Node-managed disk")+'</div>'+panel("Network",'<table class="table"><thead><tr><th>Device</th><th>Endpoint</th><th>Last seen</th><th>State</th></tr></thead><tbody>'+peerRows()+'</tbody></table>','<button class="secondary" data-go="network">Manage</button>')+panel("Quick actions",'<div class="quick-actions"><button class="primary" data-go="node">Configure node</button><button class="secondary" data-go="storage">Choose storage</button><button class="secondary" data-go="sites">Manage sites</button><button class="secondary" data-go="saved">Saved</button></div>')}
else if(k==="node"){const folder=localStorage.getItem("aweNodeFolderName")||"Node-managed storage";body='<div class="grid">'+card("Status",live.status.toUpperCase())+card("Device ID",live.device_id||"—","Shown to connections, not your profile")+card("Endpoint",live.node_address)+card("Disk",folder,"Current node storage")+'</div>'+panel("Node storage",'<div class="notice">Select an empty or dedicated folder/disk. Files selected here are imported into the node storage and then served by the node; your profile is not shared with storage peers.</div><div class="peer-form" style="margin-top:10px"><button class="primary" id="chooseFolder">Choose folder / disk</button><input id="folderFiles" type="file" webkitdirectory directory multiple style="display:none"></div><div id="folderResult" class="notice" style="margin-top:10px">'+esc(folder)+'</div>')+panel("Node identity boundary",'<div class="list"><div class="list-row"><span>Connection label</span><b>connect</b></div><div class="list-row"><span>Remote-visible identifier</span><b>'+esc(live.device_id||"device")+'</b></div><div class="list-row"><span>User profile</span><b>not published to peer UI</b></div><div class="list-row"><span>AWE identity</span><b>local cryptographic identity</b></div></div>')}
else if(k==="profile"){const p0=jsonStore("aweProfile",{displayName:"",bio:"",avatar:"A"});body=panel("Profile",'<div class="profile-card"><div class="avatar-large">'+esc((p0.avatar||"A").slice(0,1).toUpperCase())+'</div><div><h2>'+esc(p0.displayName||"AWE user")+'</h2><div class="muted">Private profile · stored on this device</div></div></div><div class="form-grid"><label>Display name<input id="profileName" value="'+esc(p0.displayName)+'" maxlength="80"></label><label>Avatar letter<input id="profileAvatar" value="'+esc(p0.avatar)+'" maxlength="1"></label><label class="wide">Bio<textarea id="profileBio" maxlength="280">'+esc(p0.bio)+'</textarea></label></div><button class="primary" id="saveProfile">Save profile</button><div class="notice" style="margin-top:10px">This profile is a UI/user profile. It is not sent as the peer connection identity.</div>')}
else if(k==="sites"){const sites=jsonStore("aweSites",[]);body=panel("Add site",'<div class="form-grid"><label>Name<input id="siteName" placeholder="My site"></label><label>Address<input id="siteUrl" placeholder="awe://site or https://…"></label><label class="wide">Description<textarea id="siteDesc" placeholder="What is this site?"></textarea></label></div><button class="primary" id="addSite">Add site</button>')+panel("My sites",sites.length?'<div class="site-list">'+sites.map((s,i)=>'<div class="site-row"><div><b>'+esc(s.name)+'</b><div class="muted">'+esc(s.url)+'</div><div class="detail">'+esc(s.description)+'</div></div><div class="row-actions"><button class="secondary" data-open-site="'+i+'">Open</button><button class="secondary danger" data-delete-site="'+i+'">Delete</button></div></div>').join("")+'</div>':'<div class="empty">No sites yet. Add your first site above.</div>')}
else if(k==="saved"){const saved=jsonStore("aweSaved",[]);body=panel("Save resource",'<div class="peer-form"><input id="saveTitle" placeholder="Title"><input id="saveUrl" placeholder="AWE site, resource or URL"><button class="primary" id="addSaved">Save</button></div>')+panel("Saved resources",saved.length?'<div class="site-list">'+saved.map((s,i)=>'<div class="site-row"><div><b>'+esc(s.title)+'</b><div class="muted">'+esc(s.url)+'</div></div><div class="row-actions"><button class="secondary" data-open-saved="'+i+'">Open</button><button class="secondary danger" data-delete-saved="'+i+'">Delete</button></div></div>').join("")+'</div>':'<div class="empty">Nothing saved yet.</div>')}
else if(k==="network"){body=panel("Connect",'<div class="peer-form"><input id="peerAddress" placeholder="127.0.0.1:41000"><button class="primary" id="connectBtn">Connect</button></div><div class="notice" style="margin-top:10px"><b>connect</b> is the only peer-facing action. The UI displays a device connection ID, not a user profile or AWE-ID.</div>')+panel("Connected devices",'<table class="table"><thead><tr><th>Device</th><th>Endpoint</th><th>Last seen</th><th>State</th></tr></thead><tbody>'+peerRows()+'</tbody></table>','<button class="secondary" id="peerRefresh">Refresh</button>')}
else if(k==="federation"){body=panel("AWENET",'<div class="grid">'+card("Node",live.device_id||"—","Local device")+card("Data centre",live.federation?.data_centre_id||"Not joined")+card("Data group",live.federation?.data_group_id||"Not joined")+card("Live links",live.status?.active_connections||0)+'</div>')+panel("Configuration",'<div class="notice">Use the existing signed .awenode, .awedc and .dgc flows below. Membership changes trigger bootstrap automatically.</div><div class="peer-form" style="margin-top:10px"><input id="fedNodeName" placeholder="Data centre name"><input id="fedEndpoint" placeholder="'+esc(live.node_address)+'"><button class="primary" id="genNode">Generate .awenode</button></div><div class="peer-form" style="margin-top:8px"><input id="fedDcId" placeholder="Data centre ID"><input id="fedDcName" placeholder="Data centre name"><button class="primary" id="genDc">Generate .awedc</button></div><div class="peer-form" style="margin-top:8px"><input id="fedGroupName" placeholder="Data group name"><input id="fedCentres" placeholder="dc-1,dc-2"><button class="primary" id="genDgc">Generate .dgc</button></div>')}
else if(k==="storage"){body='<div class="grid">'+card("Used",fmt(live.storage.used_bytes))+card("Free",fmt(live.storage.free_bytes))+card("Objects",live.storage.objects||0)+card("Healthy replicas",live.storage.healthy_replicas||0)+'</div>'+panel("Import from disk",'<div class="notice">Choose a folder and import its files into the encrypted node storage. Remote peers receive encrypted shards only.</div><div class="peer-form" style="margin-top:10px"><button class="primary" id="chooseStorageFolder">Choose folder</button><input id="storageFolderFiles" type="file" webkitdirectory directory multiple style="display:none"></div><div id="storageFolderResult" class="notice" style="margin-top:10px">No folder selected.</div>')+panel("File transfer",'<div class="peer-form"><input type="file" id="storageFile"><button class="primary" id="uploadStorage">Upload & Replicate</button></div><div id="storageUploadResult" class="notice" style="margin-top:10px">Encrypted locally before replication.</div><div class="peer-form" style="margin-top:8px"><input id="downloadFileId" placeholder="64-hex file ID"><button class="primary" id="downloadStorage">Reconstruct & Download</button></div><div id="storageDownloadResult" class="notice" style="margin-top:10px">Remote shards are reconstructed and decrypted locally.</div>')}
else if(k==="messenger"){body=panel("Messenger",'<div class="peer-form"><input id="msgRecipient" placeholder="Device / recipient AWE ID"><input id="msgText" placeholder="Message"><button class="primary" id="sendMsg">Send</button></div><div id="msgState" class="muted" style="margin-top:8px">Delivery requires remote acknowledgement.</div><div id="messageList" class="list" style="margin-top:12px"><div class="empty">Loading…</div></div>')}
else if(k==="store"){body='<div class="store-grid"><div class="card store-card"><div class="store-icon">◈</div><b>AWE Core</b><p>Core networking, identity, routing and node services.</p><span class="status"><i></i>Installed</span></div><div class="card store-card"><div class="store-icon">◎</div><b>Node Dashboard</b><p>Local management interface.</p><span class="status"><i></i>Installed</span></div><div class="card store-card"><div class="store-icon">+</div><b>AWEStore</b><p>Signed packages and capability-scoped modules.</p><span class="pill">Ready for catalog</span></div></div>')}
else if(k==="security"){body='<div class="grid">'+card("Identity","Protected","Local cryptographic identity")+card("Transport",live.transport)+card("Replay","Enabled")+card("Policy","Fail closed")+'</div>'+panel("Privacy boundary",'<div class="notice">Peers authenticate cryptographically, but the user profile is a separate local UI object. Peer lists expose only device connection metadata.</div>')}
else if(k==="diagnostics"){body=panel("Runtime diagnostics",'<div class="terminal"><div>$ node</div><div class="green">'+esc(live.device_id||"—")+'</div><div>$ peers</div><div class="green">'+live.peers.length+' connected device(s)</div></div>','<button class="primary" id="healthBtn">Run health check</button>')+panel("Result",'<div id="healthResult" class="notice">No check run yet.</div>')}
else if(k==="settings"){body=panel("Node API",'<div class="peer-form"><input id="apiBase" placeholder="http://127.0.0.1:41800" value="'+esc(apiBase())+'"><button class="primary" id="saveApi">Save & Test</button></div>')+panel("Preferences",'<div class="list"><div class="list-row"><span>Profile visibility</span><b>Private</b></div><div class="list-row"><span>Peer display</span><b>Device ID only</b></div><div class="list-row"><span>Auto refresh</span><b>5 seconds</b></div></div>')}
view.innerHTML='<div class="content"><div class="hero"><div><h1>'+p[0]+'</h1><p>'+p[1]+'</p></div><div class="actions"><button class="secondary" id="refreshBtn">Refresh</button></div></div>'+body+'</div>';bind(k)}
async function loadMessenger(){try{const d=await api("/api/messenger");const box=document.getElementById("messageList");if(box)box.innerHTML=d.messages.length?d.messages.map(m=>'<div class="list-row"><span>'+esc(m.recipient)+'</span><b>'+esc(m.state)+'</b><span>'+esc(m.text)+'</span></div>').join(""):'<div class="empty">No messages.</div>'}catch{}}
async function importFiles(files,box){let ok=0,fail=0;for(const file of [...files].slice(0,100)){if(file.size>64*1024*1024){fail++;continue}try{const bytes=new Uint8Array(await file.arrayBuffer());let hex="";for(const b of bytes)hex+=b.toString(16).padStart(2,"0");await api("/api/storage/put",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({filename:file.webkitRelativePath||file.name,data_hex:hex})});ok++}catch{fail++}}box.textContent="Imported "+ok+" file(s) into node storage"+(fail?" · "+fail+" failed":"")+".";await refresh()}
function bind(k){
 const r=document.getElementById("refreshBtn");if(r)r.onclick=async()=>{await refresh();render(k)};
 document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>render(b.dataset.go));
 document.querySelectorAll("[data-delete-site]").forEach(b=>b.onclick=()=>{const a=jsonStore("aweSites",[]);a.splice(+b.dataset.deleteSite,1);saveStore("aweSites",a);render("sites")});
 document.querySelectorAll("[data-open-site]").forEach(b=>b.onclick=()=>{const a=jsonStore("aweSites",[])[+b.dataset.openSite];if(a?.url)window.open(a.url,"_blank")});
 document.querySelectorAll("[data-delete-saved]").forEach(b=>b.onclick=()=>{const a=jsonStore("aweSaved",[]);a.splice(+b.dataset.deleteSaved,1);saveStore("aweSaved",a);render("saved")});
 document.querySelectorAll("[data-open-saved]").forEach(b=>b.onclick=()=>{const a=jsonStore("aweSaved",[])[+b.dataset.openSaved];if(a?.url)window.open(a.url,"_blank")});
 const sp=document.getElementById("saveProfile");if(sp)sp.onclick=()=>{saveStore("aweProfile",{displayName:document.getElementById("profileName").value.trim(),avatar:document.getElementById("profileAvatar").value.trim()||"A",bio:document.getElementById("profileBio").value.trim()});toast("Profile saved");render("profile")};
 const as=document.getElementById("addSite");if(as)as.onclick=()=>{const a=jsonStore("aweSites",[]),name=document.getElementById("siteName").value.trim(),url=document.getElementById("siteUrl").value.trim();if(!name||!url)return toast("Name and address are required");a.push({name,url,description:document.getElementById("siteDesc").value.trim(),created:Date.now()});saveStore("aweSites",a);toast("Site added");render("sites")};
 const av=document.getElementById("addSaved");if(av)av.onclick=()=>{const a=jsonStore("aweSaved",[]),title=document.getElementById("saveTitle").value.trim(),url=document.getElementById("saveUrl").value.trim();if(!title||!url)return toast("Title and address are required");a.push({title,url,created:Date.now()});saveStore("aweSaved",a);toast("Saved");render("saved")};
 const choose=document.getElementById("chooseFolder");if(choose)choose.onclick=async()=>{if(window.showDirectoryPicker){try{const h=await window.showDirectoryPicker();localStorage.setItem("aweNodeFolderName",h.name);document.getElementById("folderResult").textContent="Selected: "+h.name+". Choose files below to import into node storage.";toast("Node folder selected")}catch{}}else document.getElementById("folderFiles").click()};
 const ff=document.getElementById("folderFiles");if(ff)ff.onchange=()=>{const box=document.getElementById("folderResult");localStorage.setItem("aweNodeFolderName",ff.files[0]?.webkitRelativePath?.split("/")[0]||"Selected folder");importFiles(ff.files,box)};
 const cs=document.getElementById("chooseStorageFolder");if(cs)cs.onclick=()=>document.getElementById("storageFolderFiles").click();
 const sf=document.getElementById("storageFolderFiles");if(sf)sf.onchange=()=>importFiles(sf.files,document.getElementById("storageFolderResult"));
 const cb=document.getElementById("connectBtn");if(cb)cb.onclick=async()=>{const a=document.getElementById("peerAddress").value.trim();if(!a)return toast("Enter a node address");cb.disabled=true;try{await api("/api/connect?address="+encodeURIComponent(a),{method:"POST"});toast("connect requested");await refresh();render("network")}catch(e){toast("Connection failed: "+e.message)}finally{cb.disabled=false}};
 const pr=document.getElementById("peerRefresh");if(pr)pr.onclick=async()=>{await refresh();render("network")};
 const up=document.getElementById("uploadStorage");if(up)up.onclick=async()=>{const f=document.getElementById("storageFile").files[0];if(!f)return toast("Choose a file");const box=document.getElementById("storageUploadResult");await importFiles([f],box)};
 const dl=document.getElementById("downloadStorage");if(dl)dl.onclick=async()=>{const id=document.getElementById("downloadFileId").value.trim(),box=document.getElementById("storageDownloadResult");if(!/^[0-9a-fA-F]{64}$/.test(id))return toast("Enter a valid 64-hex file ID");try{const r=await api("/api/storage/get?file_id="+encodeURIComponent(id)),raw=r.data_hex||"",bytes=new Uint8Array(raw.length/2);for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(raw.slice(i*2,i*2+2),16);const a=document.createElement("a"),blob=new Blob([bytes]);a.href=URL.createObjectURL(blob);a.download=r.filename||"awep2p-file";a.click();URL.revokeObjectURL(a.href);box.textContent="Downloaded "+(r.filename||"file")}catch(e){box.textContent="Download failed: "+e.message}};
 const sm=document.getElementById("sendMsg");if(sm)sm.onclick=async()=>{const recipient=document.getElementById("msgRecipient").value.trim(),message=document.getElementById("msgText").value.trim();if(!recipient||!message)return toast("Recipient and message are required");try{const r=await api("/api/messenger/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipient,text:message})});document.getElementById("msgState").textContent="Delivery: "+r.status;await loadMessenger()}catch(e){document.getElementById("msgState").textContent="Send failed: "+e.message}};
 const sa=document.getElementById("saveApi");if(sa)sa.onclick=async()=>{localStorage.setItem("aweApiBase",document.getElementById("apiBase").value.trim().replace(/\/$/,""));await refresh();render("settings");toast("API endpoint saved")};
 const hb=document.getElementById("healthBtn");if(hb)hb.onclick=async()=>{try{const x=await api("/api/health");document.getElementById("healthResult").textContent="Healthy · "+JSON.stringify(x)}catch(e){document.getElementById("healthResult").textContent="Health check failed: "+e.message}};
 const gen=async(kind,payload)=>{try{const r=await api("/api/federation/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,...payload})});if(r.status!=="generated")throw new Error(r.error||"generation failed");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([r.content],{type:"application/json"}));a.download=r.filename;a.click();toast("Generated "+r.filename)}catch(e){toast(e.message)}};
 const gn=document.getElementById("genNode");if(gn)gn.onclick=()=>gen("awenode",{name:document.getElementById("fedNodeName").value.trim()||"AWE Data Centre",endpoint:document.getElementById("fedEndpoint").value.trim()||live.node_address,bootstrap:[]});
 const gd=document.getElementById("genDc");if(gd)gd.onclick=()=>gen("awedc",{data_centre_id:document.getElementById("fedDcId").value.trim(),name:document.getElementById("fedDcName").value.trim()||"AWE Data Centre",endpoints:[live.node_address]});
 const gg=document.getElementById("genDgc");if(gg)gg.onclick=()=>gen("dgc",{owner_data_centre_id:live.federation?.data_centre_id||"",name:document.getElementById("fedGroupName").value.trim()||"AWE Data Group",data_centre_ids:(document.getElementById("fedCentres").value||"").split(",").map(x=>x.trim()).filter(Boolean)});
}
navs.forEach(n=>n.addEventListener("click",()=>render(n.dataset.view)));
document.getElementById("avatarBtn").onclick=()=>render("profile");
(async()=>{await refresh();render("dashboard");setInterval(async()=>{await refresh();if(title.textContent===pages.dashboard[0])render("dashboard")},5000)})();