[package]
name = "awe-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "awep2p-desktop"
path = "src/main.rs"

[dependencies]
awep2p-core = { path = "../../core" }
eframe = "0.28.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader"] }
